### ISSUE TITLE
Fine tuning and release-ready

### ISSUE THREAD

**Issue by VinayGupta23** [bitloks/Gravitas#15]
The following miscellaneous enhancements and bug fixes are required to bring the app to release stage.

1. "No results found" message on Search Box crashes (Update: **On pressing search, two different functions are invoked. Fix needed.**)
2. Home page banner does not hide when scrolling or resizing window
3. The social media connect buttons need a facelift
4. Settings page cleanup (or remove if not required)
5. Event list in category view could be slightly revamped
6. Spacing adjustments in Event detailed view
7. Put your name first in developer list :)

**Comment by ripdollar** [comment]
Bug {1} is fixed.

**Comment by bitloks** [comment]
all solved
