### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by VinayGupta23** [bitloks/Gravitas#7]
A .gitignore file is needed to avoid unnecessary commits due to maintenance and OS generated files. (Example, `.suo` file.)

Please refer to online Q&A for help on adding a `.gitignore` after having created a repository.

**Comment by VinayGupta23** [comment]
The .gitignore file is EMPTY.

Is this a joke? Please google on how to add a .gitignore file after creating a repo and see what you've to do.

**Comment by bitloks** [comment]
Sorry guess the  changes to the file was not saved and i committed wrongly but now i have double checked and its correct :) . and currently waiting for harshal to give me api link when its  done.Meanwhile trying to add push notifications to the app.
